name: test_projcet_invan
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_generator: ^2.0.1
  hive_flutter: ^1.1.0
  get_it: ^7.6.4
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  gap: ^3.0.1
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  url_launcher: ^6.2.5
  permission_handler: ^11.3.0
  internet_connection_checker: ^1.0.0+1
  http: ^1.2.2
  maps_launcher: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  bloc_test: ^9.1.4

flutter:
  uses-material-design: true
