import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:test_projcet_invan/bloc/auth_bloc/auth_bloc.dart';
import 'package:test_projcet_invan/data/models/auth_user_model/auth_user_model.dart';
import 'package:test_projcet_invan/data/services/injector_container.dart';
import 'package:test_projcet_invan/ui/app_routes.dart';
part 'auth_screen.dart';
part 'widgets/auth_screen_textfield.dart';
part 'mixin/auth_screen_mixin.dart';